### PR TITLE
Some major issues taken care of (probably).

### PR DESCRIPTION
**Pull request by athityakumar**
1. ( issue #43 ) Read more - done. Now, users will only see a small preview from each post and they will see those lengthy posts only if they want to.
2. ( issue #44 ) Flat-UI done. Better responsive on mobile screens than the previous one. And yet, much lighter-weight as all CSS & JS includes are done via CDN.
   The `masonry` view of the posts in cards probably rules out the necessity for pagination. 

Suggest your opinions, @icyflame @vivekiitkgp @DefCon-007 @hargup @AvijitGhosh82

### CODE REVIEW

**Comment by raivivek** [comment]
I was wondering if you can incorporate a small request. Currently, naarad seems to be using Roboto Light as its display. Somehow, I don't find Roboto to be a suitable font for reading text.

Would you like to try Liberation Sans, Linux Libertine?

**Comment by athityakumar** [comment]
@vivekiitkgp : Added liberation sans, but doesn't seem to have much difference.

**Comment by hargup** [comment]
Is there a way I can preview the changes without locally building the pull?

**Comment by athityakumar** [comment]
@hargup - You can copy paste just the `docs/index.html` file. (Ofcourse, it won't have the favicon - but it won't matter much for reviewing.)

**Comment by athityakumar** [comment]
Oops, just noticed that Wiki , Github & Facebook links haven't been given to point yet. Can someone insert those links within this PR? Else, I'll do it tomorrow.

**Comment by athityakumar** [comment]
@hargup - BTW , you can preview it here : https://athityakumar.github.io/naarad-source/

**Comment by raivivek** [comment]
@athityakumar Looks neat. Thanks for the effort. Also, you may wish to experiment a bit with colors. Like, replace black with a grayish tone to reduce straining contrast.

**Comment by athityakumar** [comment]
@vivekiitkgp : Thanks. Actually, I was trying to include metakgp's logo instead of the hash symbol on navbar. But I couldn't find a good hexadecimal color for navbar. So, I just removed the logo, and used this color for navbar. 

The contrast was an intended one, as nothing else distinguished properly the body of the page from navbar. So, please tell me if you know the hexadecimal color of the black in metakgp logo, or do suggest some other color.

**Comment by hargup** [comment]
@athityakumar Thanks for you work. I prefer the current theme, this one looks too crowded to me, also this one requires more effort to browse as I have to often click read more to read the story to find that there is only one more line. In the current theme I can just scroll through all the content.

**Comment by athityakumar** [comment]
@hargup : But that's the point. You aren't forced to read / scroll through the posts you don't to read.

**Comment by hargup** [comment]
> You aren't forced to read / scroll through the posts you don't to read. 

But I'm forced to make a lot of clicks. We can put this theme on a beta release to something like `naarad.metakgp.org/beta` and ask for views of other people. Also people should be able to switch between the two views the card one this one.

**Review by icyflame — CHANGES_REQUESTED** [review]
@athithyakumar

Clicking on the `[...]` leads to this:

image

Whereas clicking on the `Read More` button leads to:

image

The second seems to be the one that's intended.

Note that in posts with a photo, both the previews look the same.

**Comment by athityakumar** [comment]
@icyflame : Made the required change. Any other changes required?

**Comment by DefCon-007** [comment]
@athityakumar : Clicking on the first post's [...] i.e. of awaaz is taking wrong image.

**Comment by athityakumar** [comment]
@DefCon-007 : The update one doesn't seem to be having that error. The preview that I posted earlier isn't updated yet. So, use this PR's index.html file to check.

**Comment by raivivek** [comment]
May be just make it a lighter shade of black. Perhaps #444

## 

https://vivekiitkgp.github.io

**Comment by DefCon-007** [comment]
@athityakumar : Should we merge it and get Naarad V2.0 ?

**Review by icyflame — APPROVED** [review]

**Comment by icyflame** [comment]
@athityakumar @DefCon-007 LGTM

**Comment by athityakumar** [comment]
@DefCon-007  @icyflame : Just one issue - the order of the cards is something we have to fix before merging. It's alright in mobile screen, but in laptop screen - these cards are stacked first along left column, then middle & right columns. So, we should probably have 2 json files - one for mobile view (original) and one for other screens' view (tweak the original json). And then Bootstrap classes like `sm-only` for original json and `md-only` , `lg-only` for tweaked json.

**Comment by icyflame** [comment]
@athityakumar Design wise tweaking the JSON is a bad idea. There should be a single json, which can be rendered whichever way that we want it to be rendered. Would it be better if you just started showing every third entry in the first column, every second one in the second column, etc, assuming there are three columns?

**Comment by athityakumar** [comment]
@icyflame : I don't think Django templating allows python code to be used like that in the template file. That's why it would be useful if we could have another json that would swap 2nd and (n/3 + 1)th element and so on.

**Comment by icyflame** [comment]
Instead of [this line](https://github.com/metakgp/naarad-source/blob/master/feed.tmpl#L67), do:

`for i = 0; i < data.len; i += 3`
`for i = 1; i < data.len; i += 3`
`for i = 2; i < data.len; i += 3`

Remember that `for ... in ...` is not the only way a for loop can be written.

**Comment by icyflame** [comment]
@athityakumar @DefCon-007 See the previous comment for horizontal UI.

**Comment by athityakumar** [comment]
@icyflame : Cool, we can use these 3 for loops for big screens & the existing loop for mobile display. 👍

**Review by icyflame — CHANGES_REQUESTED** [review]
Instead of [this line](https://github.com/metakgp/naarad-source/blob/master/feed.tmpl#L67), do:

`for i = 0; i < data.len; i += 3`
`for i = 1; i < data.len; i += 3`
`for i = 2; i < data.len; i += 3`

Remember that `for ... in ...` is not the only way a for loop can be written.

**Comment by DefCon-007** [comment]
> Cool, we can use these 3 for loops for big screens & the existing loop for mobile display. 

What if use the three loops for both the displays ? Will it be a problem ? 

cc @athityakumar

**Comment by athityakumar** [comment]
@DefCon-007 : We can, but the existing loop is already the proper one for mobile displays. We don't have to change it.

**Comment by DefCon-007** [comment]
But having loops according to display seems not right to me.

**Comment by athityakumar** [comment]
@DefCon-007 : Yeah, but making a `horizontal masonry` is just too difficult, and that's why they came up with a `vertical masonry`. That's why even bootstrap has done it like that. And I don't think there is another way to proceed for us. 

@icyflame : Any other idea on how we can make this `masonry` work properly for our case?

**Comment by icyflame** [comment]
> Cool, we can use these 3 for loops for big screens & the existing loop for mobile display.

@athityakumar @DefCon-007 this is the way to go. Decide on the basis of the viewport width. There's no flaw here, this is often done because of horizontal stacking being harder than columns.

relevant-xkcd

**Comment by athityakumar** [comment]
@icyflame - I was picturing exactly the same meme template, when I wrote my last comment. Ofcourse, the meme text was different I guess -

"I want the stuff to be centered horizontally..."
"Cool, just a flex box and css tweaking will do the job."
"... and vertically"
"I need a research team & 5 years"

**Comment by icyflame** [comment]
@athityakumar That is also another XKCD. I was searching for that, but couldn't find it.

**Comment by athityakumar** [comment]
@icyflame @DefCon-007 : Seems like the 3 for loops aren't going to solve our problem. Have a look at how the `masonry` decides the order of cards on bigger screens. I'm writing a new block of code to take care of that.

image
image
image
image
image

**Comment by icyflame** [comment]
> Seems like the 3 for loops aren't going to solve our problem. Have a look at how the masonry decides the order of cards on bigger screens.

@athityakumar I don't understand, what's the problem here? The first column will have 1, 4, 7 ... and second column will have 2, 5, 8, ... and third column will have 3, 6, 9, ... How have you written the loops? What do you mean the masonry decides the order?

**Comment by athityakumar** [comment]
@icyflame : Just a minor issue for when n%3 = 1. Say, see n=10 case => have a look at the screenshot.
After just those 3 loops, modified array will be [1,4,7,10,2,5,8,3,6,9] => the `masonry` then organizes them as `1,4,7,10` for left cloumn, `2,5,8,3` for middle column (this misplaced 3 is the bug) & `6,9` for right column.

**Comment by athityakumar** [comment]
@icyflame @DefCon-007 : And this is what I meant when I said that the `masonry`decides the order depending on the size of content. 

image

Due to this, the top most & bottom most rows have some anomalies, but the middle content is perfect.
Anomaly at top : image

Anomaly at bottom : image

Proper at middle : image

**Comment by icyflame** [comment]
@athityakumar This is expected. Not to be treated as an issue, until we can come up with a better design to show all the information. Is this ready for review?

**Review by icyflame — APPROVED** [review]

**Comment by athityakumar** [comment]
@icyflame : Yeah, sure. Any other change(s) required?

P.S - I do have a conspiracy theory now that `lazyload` is interfering with `masonry` to render some recent posts to the bottom & some very very early news to the top. Maybe `masonry` does place them properly into 3 columns, then `lazyload` loads the images, resulting in shifting of some posts - resulting in anomalies.

**Comment by DefCon-007** [comment]
@athityakumar : How about changing the font ?

**Comment by athityakumar** [comment]
@DefCon-007 : @vivekiitkgp suggested to change the font to the current font (Liberation Sans). Have a look at the conversation above.

**Comment by raivivek** [comment]
May be I meant to say Linux Libertine. Give it a shot maybe? Free, open
source, great font.

--
https://vivekiitkgp.github.io

**Comment by icyflame** [comment]
@athityakumar This PR is getting too big. I am merging this in for now, please create a new patch with the font changed to Linux Libertine, and we will see how that looks.

**Pull request merged**
