### PR TITLE
Integrates Datatable with Naarad

### PR DESCRIPTION
**Pull request by athityakumar**
Integrates [DataTable](https://datatables.net/) into Naarad. This fixes : 

- Search
- Pagination
- Proper order of posts without having 2 sets of `data` lists for mobile and laptop screens

Demo : https://athityakumar.github.io/naarad-source/

Ping @ghostwriternr @icyflame @hargup @DefCon-007 @vivekiitkgp @americast @amrav

### CODE REVIEW

**Comment by raivivek** [comment]
Hmm. This simplifies quite a bit of stuff. Cool. :+1:

**Comment by athityakumar** [comment]
Is any enhancement required, or is the PR ready to be merged?

**Comment by americast** [comment]
@athityakumar A minor issue: After moving to the next page, it scrolls down to the bottom of the new page.

Also, I think we should integrate the "search" and "no. of entries" into the floating bar on top. But that can be done later too.

**Comment by icyflame** [comment]
@athityakumar Had a look at the demo, looks good. There is a lot of free space on the left and right of the central column. Maybe you could use it better? 

I know that grid systems were creating a problem earlier, a good approach to solve that might be to create "categories":

1. First column consists of the Metakgp Facebook page
2. Second column is campus news: Awaaz, ScholsAve
3. Third column consists of institute official pages: TSG, A-Cell, Inter-IIT, etc.

The categories can be different and must be easily editable later, but I think this is a better approach to using the space that we have well. The current approach is good for mobile screens, but for laptop and desktop screens, there's just too much wasted space on the screen. Think about this!

If you don't want to do it, of course you should go ahead and merge this PR. 2 weeks is enough time for everyone to chime in with their opinion.

**Comment by athityakumar** [comment]
Adding the `Categories` and `Datatables' Dropdown and Search on Navbar` as issues. Merging this Pull Request.

**Comment by athityakumar** [comment]
Added issues #81 and #82.

**Pull request merged**
