### PR TITLE
time stamp

### PR DESCRIPTION
**Pull request by americast**
Resolving issue #52.
Changes made only in fscraper.py and feed.tmpl

Gramercy,
Sayan Sinha.
(kwoc_2016 student)

### CODE REVIEW

**Comment by DefCon-007** [comment]
@americast post a screenshot too

**Comment by americast** [comment]
Screenshot:
2016-12-13-180922_1366x768_scrot
The last updated time is shown at the top right corner.

**Review by DefCon-007 — APPROVED** [review]

**Comment by DefCon-007** [comment]
@athityakumar @icyflame @hargup : Seems cool to me what do you say ?

**Comment by icyflame** [comment]
Screenshot looks good.

**Review by icyflame — APPROVED** [review]

**Comment by athityakumar** [comment]
@americast - Can we have the last-updated timestamp like those timestamps on the other cards? Like, `Last updated on dd-mm-yyyy at hh:mm AM IST`.

What say, @DefCon-007 @icyflame @hargup ?

**Comment by DefCon-007** [comment]
@athityakumar I think that will look odd. The present timestamp looks nice to me.

**Review by athityakumar — APPROVED** [review]

**Review by athityakumar — COMMENTED** [review]
@americast : Can you provide a screenshot of the timestamp in mobile view? If that looks good, we can merge this PR in.

**Comment by americast** [comment]
Made a small change to incorporate mobile view. Screenshots:

Mobile view:
2016-12-17-103118_1366x768_scrot


Desktop view:
2016-12-17-102842_1366x768_scrot

**Comment by athityakumar** [comment]
The screenshots are looking good. Squash-merging this in. :+1:

**Pull request merged**
