### PR TITLE
Added support for videos

### PR DESCRIPTION
**Pull request by DefCon-007**

### CODE REVIEW

**Review by athityakumar — COMMENTED** [review]
What is that `defconkgp.json` supposed to do?

**Comment by DefCon-007** [comment]
@athityakumar I created a dummy page to test video. It is the json file of it. I thought to push it to because it can help in testing in future. We will remove it from fbscrapper.py while deploying to naarad.

**Comment by athityakumar** [comment]
But it's working now right? So, leave out that file from this PR?

**Comment by DefCon-007** [comment]
@athityakumar : Removed the json file and also removed page from fbscrapper.py 
P.S. : index.html is not updated. i.e. post from dummy page are still there

**Comment by athityakumar** [comment]
@DefCon-007 : Merging it. And for the html file, the cron job will run frontend.py and take care of it.

**Pull request merged**
